# Generated by Django 4.1.5 on 2023-01-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siswa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasiswa",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
            ),
        ),
    ]
