# Generated by Django 4.1.5 on 2023-01-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0001_initial"),
        ("siswa", "0002_alter_datasiswa_jenis_kelamin"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasiswa",
            name="asalSekolah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sekolah.sekolah",
            ),
        ),
    ]
