# Generated by Django 4.1.5 on 2023-01-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siswa", "0003_datasiswa_asalsekolah"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasiswa",
            old_name="asalSekolah",
            new_name="asal_Sekolah",
        ),
        migrations.RenameField(
            model_name="datasiswa",
            old_name="noTelepon",
            new_name="no_Telepon",
        ),
    ]
