# Generated by Django 4.1.5 on 2023-01-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0002_rename_jenissekolah_sekolah_jenis_sekolah_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sekolah",
            options={"ordering": ["-id"], "verbose_name_plural": "sekolah"},
        ),
        migrations.RenameField(
            model_name="sekolah",
            old_name="no_Telpon",
            new_name="Telp",
        ),
        migrations.RemoveField(
            model_name="sekolah",
            name="jenis_Sekolah",
        ),
        migrations.AddField(
            model_name="sekolah",
            name="NPSN",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="kabupaten_atau_kota",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="kecamatan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="provinsi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("S", "Swasta"), ("N", "Negeri")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sekolah",
            name="nama",
            field=models.CharField(max_length=10),
        ),
    ]
