# Generated by Django 4.1.5 on 2023-01-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sekolah",
            "0003_alter_sekolah_options_rename_no_telpon_sekolah_telp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sekolah",
            name="NPSN",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="sekolah",
            name="nama",
            field=models.CharField(max_length=50),
        ),
    ]
