# Generated by Django 4.1.5 on 2023-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0004_alter_sekolah_npsn_alter_sekolah_nama"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sekolah",
            name="NPSN",
        ),
        migrations.AlterField(
            model_name="sekolah",
            name="status",
            field=models.CharField(
                choices=[("S", "Swasta"), ("N", "Negeri")], default="0", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="npsn",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
