# Generated by Django 4.1.5 on 2023-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0005_remove_sekolah_npsn_alter_sekolah_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sekolah",
            name="npsn",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="sekolah",
            name="status",
            field=models.CharField(
                choices=[("S", "Swasta"), ("N", "Negeri")], default="", max_length=1
            ),
        ),
    ]
