# Generated by Django 4.1.5 on 2023-01-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="perusahaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("web", models.CharField(blank=True, max_length=100, null=True)),
                ("noTelp", models.CharField(max_length=20)),
                ("alamat", models.TextField(blank=True, null=True)),
                (
                    "jenisSekolah",
                    models.CharField(
                        choices=[
                            ("PT", "perseroan terbatas"),
                            ("CV", "Commanditaire Vennootschap"),
                            ("VOF", "vennootschap onder firma"),
                            ("PRS", "PT. PERMODALAN NASIONAL MADANI (PERSERO)"),
                            ("KO", "Koperasi"),
                            ("PO", "PERSEORANGAN"),
                        ],
                        max_length=3,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "perusahaan",
                "ordering": ["-id"],
            },
        ),
    ]
