# Generated by Django 4.1.5 on 2023-01-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perusahaan", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perusahaan",
            old_name="jenisSekolah",
            new_name="jenis_Sekolah",
        ),
        migrations.RenameField(
            model_name="perusahaan",
            old_name="noTelp",
            new_name="no_Telpon",
        ),
    ]
