# Generated by Django 4.1.5 on 2023-01-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perusahaan", "0002_rename_jenissekolah_perusahaan_jenis_sekolah_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perusahaan",
            old_name="jenis_Sekolah",
            new_name="jenis_Perusahaan",
        ),
    ]
